def autoTakeLocation():    
    import pyautogui
    latLocminus = pyautogui.locateOnScreen('img/latitudeminus.png')
    if latLocminus == None:
        print('nie wykryto ujemnych loc')
        latLoc = pyautogui.locateOnScreen('img/latitude.png')
        if latLoc == None:
            print('nie wykryto dodatnich loc')  
            print("Nie wykryto wskazanej lokalizacji. Lub okno przegladarki \nnie znajduje się w obrębie pierwszego ekranu. \nZaznacz wybrany punkt na mapie i uruchom \nprogram ponownie.")
        else:
            # Jeżeli LAT jest dodatnie
            pyautogui.click(latLoc)
            pyautogui.move(32, 0)
            pyautogui.doubleClick()
            pyautogui.hotkey('ctrl', 'c')
            pyautogui.click(button='right')
            pyautogui.move(15, 15)
            pyautogui.click()
            latLocins = pyautogui.locateOnScreen('img/nslat.png')
            pyautogui.click(latLocins)
            pyautogui.move(25, 0)
            pyautogui.doubleClick()
            pyautogui.hotkey('ctrl', 'v')

            pyautogui.click(latLoc)
            pyautogui.move(60, 0)
            pyautogui.doubleClick()
            pyautogui.hotkey('ctrl', 'c')
            pyautogui.click(button='right')
            pyautogui.move(15, 15)
            pyautogui.click()
            latLocins = pyautogui.locateOnScreen('img/nslat.png')
            pyautogui.click(latLocins)
            pyautogui.move(65, 0)
            pyautogui.doubleClick()
            pyautogui.hotkey('ctrl', 'v')
            pyautogui.typewrite('01')
    else:
        # Jeżeli LAT jest ujemne
        pyautogui.click(latLocminus)
        pyautogui.move(24, 0)
        pyautogui.doubleClick()
        pyautogui.hotkey('ctrl', 'c')
        pyautogui.click(button='right')
        pyautogui.move(15, 15)
        pyautogui.click()
        latLocins = pyautogui.locateOnScreen('img/nslat.png')
        pyautogui.click(latLocins)
        pyautogui.move(25, 0)
        pyautogui.doubleClick()
        pyautogui.hotkey('ctrl', 'v')

        pyautogui.click(latLocminus)
        pyautogui.move(32, 0)
        pyautogui.doubleClick()
        pyautogui.hotkey('ctrl', 'c')
        pyautogui.click(button='right')
        pyautogui.move(15, 15)
        pyautogui.click()
        latLocins = pyautogui.locateOnScreen('img/nslat.png')
        pyautogui.click(latLocins)
        pyautogui.move(25, 0)
        pyautogui.click(button='left')
        pyautogui.hotkey('ctrl', 'v')  

        pyautogui.click(latLocminus)
        pyautogui.move(60, 0)
        pyautogui.doubleClick()
        pyautogui.hotkey('ctrl', 'c')
        pyautogui.click(button='right')
        pyautogui.move(15, 15)
        pyautogui.click()
        latLocins = pyautogui.locateOnScreen('img/nslat.png')
        pyautogui.click(latLocins)
        pyautogui.move(65, 0)
        pyautogui.doubleClick()
        pyautogui.hotkey('ctrl', 'v')
        pyautogui.typewrite('01')

    lngLocminus = pyautogui.locateOnScreen('img/longitudeminus.png')
    if lngLocminus == None:
        print('nie wykryto ujemnych loc')
        lngLoc = pyautogui.locateOnScreen('img/longitude.png')
        if lngLoc == None:
            print('nie wykryto dodatnich loc')  
            print("Nie wykryto wskazanej lokalizacji. Lub okno przegladarki \nnie znajduje się w obrębie pierwszego ekranu. \nZaznacz wybrany punkt na mapie i uruchom \nprogram ponownie.")
        else:
            pyautogui.click(lngLoc)
            pyautogui.move(36, 0)
            pyautogui.doubleClick()
            pyautogui.hotkey('ctrl', 'c')
            pyautogui.click(button='right')
            pyautogui.move(15, 15)
            pyautogui.click()
            lngLocins = pyautogui.locateOnScreen('img/welng.png')
            pyautogui.click(lngLocins)
            pyautogui.move(25, 0)
            pyautogui.doubleClick()
            pyautogui.hotkey('ctrl', 'v')


            pyautogui.click(lngLoc)
            pyautogui.move(60, 0)
            pyautogui.doubleClick()
            pyautogui.hotkey('ctrl', 'c')
            pyautogui.click(button='right')
            pyautogui.move(15, 15)
            pyautogui.click()
            latLocins = pyautogui.locateOnScreen('img/welng.png')
            pyautogui.click(lngLocins)
            pyautogui.move(65, 0)
            pyautogui.doubleClick()
            pyautogui.hotkey('ctrl', 'v')
            pyautogui.typewrite('01')
    else:
        
        pyautogui.click(lngLocminus)
        pyautogui.move(30, 0)
        pyautogui.doubleClick()
        pyautogui.hotkey('ctrl', 'c')
        pyautogui.click(button='right')
        pyautogui.move(15, 15)
        pyautogui.click()
        lngLocins = pyautogui.locateOnScreen('img/welng.png')
        pyautogui.click(lngLocins)
        pyautogui.move(25, 0)
        pyautogui.doubleClick()
        pyautogui.hotkey('ctrl', 'v')

        pyautogui.click(lngLocminus)
        pyautogui.move(36, 0)
        pyautogui.doubleClick()
        pyautogui.hotkey('ctrl', 'c')
        pyautogui.click(button='right')
        pyautogui.move(15, 15)
        pyautogui.click()
        lngLocins = pyautogui.locateOnScreen('img/welng.png')
        pyautogui.click(lngLocins)
        pyautogui.move(25, 0)
        pyautogui.click(button='left')
        pyautogui.hotkey('ctrl', 'v')

        pyautogui.click(lngLocminus)
        pyautogui.move(60, 0)
        pyautogui.doubleClick()
        pyautogui.hotkey('ctrl', 'c')
        pyautogui.click(button='right')
        pyautogui.move(15, 15)
        pyautogui.click()
        latLocins = pyautogui.locateOnScreen('img/welng.png')
        pyautogui.click(lngLocins)
        pyautogui.move(65, 0)
        pyautogui.doubleClick()
        pyautogui.hotkey('ctrl', 'v')
        pyautogui.typewrite('01')

autoTakeLocation()
